prompts:
  viral_hooks:
    en: |
      EXAMPLES OF HIGH‑COMMENT, POLARIZING VIRAL HOOKS (use as inspiration):
      - "nobody talks about this, but it ruins most relationships."
      - "disagree with me if you want, but this is the truth."
      - "most parents are doing this wrong. here's why."
      - "this isn't just unpopular—it's fact."
      - "this mindset will hold your kid back for life."
      - "you're not lazy. you were taught the wrong system."
      - "what if i told you there's a simple way to achieve [RESULT]?"
      - "stop scrolling if you want to discover [SECRET]"
      - "everything you knew about [TOPIC] is 100% wrong"
      - "here's why 99% of [AUDIENCE] fail at [TOPIC]"
    es: |
      EJEMPLOS DE HOOKS VIRALES POLÉMICOS Y GENERADORES DE COMENTARIOS (usa como inspiración):
      - "nadie habla de esto, pero arruina la mayoría de las relaciones."
      - "puedes no estar de acuerdo, pero esta es la verdad."
      - "la mayoría de los padres lo hacen mal. aquí está el porqué."
      - "esto no solo es impopular — es un hecho."
      - "esta mentalidad frenará a tu hijo de por vida."
      - "no eres perezoso, te enseñaron el sistema equivocado."
      - "¿sabías que hay una forma sencilla de conseguir [RESULTADO]?"
      - "deja de desplazarte si quieres descubrir [SECRETO]"
      - "todo lo que sabías sobre [TEMA] es 100% erróneo"
      - "aquí tienes por qué el 99 % de [AUDIENCE] fracasa en [TEMA]"

  organic_hooks:
    en: |
      EXAMPLES OF ORGANIC EDUCATIONAL HOOKS (use as inspiration):
      - "3 things i learned about [TOPIC] after years of experience"
      - "why [CONCEPT] actually works (explained simply)"
      - "the difference between [OPTION A] and [OPTION B] nobody explains"
      - "5 signs you're doing [ACTIVITY] correctly"
      - "what actually happens when [PROCESS] – the science behind it"
      - "common [AREA] mistakes you can easily avoid"
      - "how [CONCEPT] actually works – step‑by‑step guide"
      - "important [TOPIC] lessons that took me years to learn"
    es: |
      EJEMPLOS DE HOOKS ORGÁNICOS EDUCATIVOS (usa como inspiración):
      - "3 cosas que aprendí sobre [TEMA] después de años de experiencia"
      - "por qué [CONCEPTO] funciona realmente (explicado simple)"
      - "la diferencia entre [OPCIÓN A] y [OPCIÓN B] que nadie explica"
      - "5 señales de que estás haciendo [ACTIVIDAD] correctamente"
      - "qué pasa realmente cuando [PROCESO] – la ciencia detrás"
      - "errores comunes en [ÁREA] que puedes evitar fácilmente"
      - "cómo funciona realmente [CONCEPTO] – guía paso a paso"
      - "lecciones importantes sobre [TEMA] que me tomó años aprender"

  organic_instructions: |
    ORGANIC CONTENT MODE – CRITICAL REQUIREMENTS:
    - Generate PURELY EDUCATIONAL content with zero promotional elements
    - Focus on sharing genuine knowledge, insights, and practical tips
    - No mentions of products, services, apps, tools, or anything that could be construed as promotional
    - No calls‑to‑actions for purchases, sign‑ups, downloads, or external links
    - Content should feel like a helpful teacher sharing valuable knowledge
    - Use conversational, authentic tone focused on education
    - End with engagement questions about learning experiences or knowledge sharing
    - No "limited time," "special offer," "our solution," "buy now," or similar language
    - The goal is to provide pure value and education to the audience

  slide_instructions: |
    # SLIDE CREATION GUIDELINES

    ## VIRAL / HIGH‑COMMENT MODE
    - **Hook (slide 1)**: Make a bold, polarizing, or contrarian claim that sparks debate.
      * Trigger emotion or curiosity; challenge a widely held belief.
    - **Slides 2–6**: Deliver short, punchy “truth‑bomb” statements or tips that deepen the controversy or illuminate your viewpoint.
      * Each slide must stand alone and push readers to agree or disagree.
      * Keep text minimal: one core idea per slide, lowercase, no emojis or markdown.
    - **CTA (slide 7)**: End with STRONG comment bait.
      * Ask an irresistible question (“agree or disagree?”, “is this normal or insane?”).
      * Never ask for purchases or external actions.

    ## ORGANIC EDUCATIONAL MODE
    - **Hook (slide 1)**: One scroll‑stopping sentence that promises clear insight.
    - **Slides 2–6**: Five actionable, no‑fluff tips readers can apply immediately.
    - **CTA (slide 7)**: Invite discussion or sharing of experiences (no promotions).

    _General rules for both modes_:
    - No language implying a sale or promotion.
    - Tone: conversational, authentic, lowercase.
    - Total slides: exactly 7.

  json_format: |
    JSON format:
    {
      "title": "authentic lowercase title that promises real value",
      "hook": "polarizing or educational hook (slide 1)",
      "slides": ["slide 2 text", "slide 3 text", "slide 4 text", "slide 5 text", "slide 6 text"],
      "cta": "strong comment‑bait CTA (slide 7)",
      "searchTerms": ["visual 1", "visual 2", "visual 3", "visual 4", "visual 5", "visual 6", "visual 7"]
    }
